/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Told } from "./Told";
export * as factories from "./factories";
export { Told__factory } from "./factories/Told__factory";
